"""second update

Revision ID: 1078920783b3
Revises: 0126d9492ccb
Create Date: 2024-04-29 21:13:51.079162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1078920783b3'
down_revision = '0126d9492ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_list',
    sa.Column('user_id', sa.String(length=250), nullable=False),
    sa.Column('book_isbn', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['book_isbn'], ['books.isbn'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'book_isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourite_list')
    # ### end Alembic commands ###
