"""second/add_lazada_table

Revision ID: 8903ceb8f5fe
Revises: c2d8d4753e67
Create Date: 2024-04-30 22:16:53.572228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8903ceb8f5fe'
down_revision = 'c2d8d4753e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lazada_books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isbn', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=30), nullable=True),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lazada_books')
    # ### end Alembic commands ###
