"""adding new book table

Revision ID: 8b1834f6fd82
Revises: f0615d38c967
Create Date: 2024-04-24 15:47:51.807015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1834f6fd82'
down_revision = 'f0615d38c967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opentrolley_books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isbn', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=30), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opentrolley_books')
    # ### end Alembic commands ###
