"""1

Revision ID: a961c992abdc
Revises: 
Create Date: 2024-05-12 11:11:56.020097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a961c992abdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('isbn', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('description', mysql.LONGTEXT(), nullable=True),
    sa.Column('url', mysql.LONGTEXT(), nullable=True),
    sa.Column('average_rating', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.create_table('new_arrivals',
    sa.Column('isbn', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('description', mysql.LONGTEXT(), nullable=True),
    sa.Column('url', mysql.LONGTEXT(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=True),
    sa.Column('full_name', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=True)

    op.create_table('favourite_list',
    sa.Column('user_id', sa.String(length=250), nullable=False),
    sa.Column('book_isbn', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['book_isbn'], ['books.isbn'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'book_isbn')
    )
    op.create_table('interactions',
    sa.Column('user_id', sa.String(length=250), nullable=False),
    sa.Column('book_isbn', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['book_isbn'], ['books.isbn'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'book_isbn')
    )
    op.create_table('lazada_books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isbn', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=30), nullable=True),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('opentrolley_books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isbn', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=30), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('ratings',
    sa.Column('user_id', sa.String(length=250), nullable=False),
    sa.Column('book_isbn', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_isbn'], ['books.isbn'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'book_isbn')
    )
    op.create_table('reviews',
    sa.Column('user_id', sa.String(length=250), nullable=False),
    sa.Column('book_isbn', sa.String(length=255), nullable=False),
    sa.Column('review', mysql.LONGTEXT(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_isbn'], ['books.isbn'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'book_isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('ratings')
    op.drop_table('opentrolley_books')
    op.drop_table('lazada_books')
    op.drop_table('interactions')
    op.drop_table('favourite_list')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))

    op.drop_table('users')
    op.drop_table('new_arrivals')
    op.drop_table('books')
    # ### end Alembic commands ###
