"""first db creation

Revision ID: d0efe9856ee5
Revises: 
Create Date: 2024-04-30 22:05:50.937104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0efe9856ee5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isbn', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('description', mysql.LONGTEXT(), nullable=True),
    sa.Column('url', mysql.LONGTEXT(), nullable=True),
    sa.Column('average_rating', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=True),
    sa.Column('full_name', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('favourite_list',
    sa.Column('user_id', sa.String(length=250), nullable=False),
    sa.Column('book_isbn', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['book_isbn'], ['books.isbn'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'book_isbn')
    )
    op.create_table('lazadas_books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isbn', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=30), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opentrolley_books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('isbn', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=30), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['books.isbn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opentrolley_books')
    op.drop_table('lazadas_books')
    op.drop_table('favourite_list')
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
